# Generated by Django 4.2.6 on 2023-10-11 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0002_historialmedicamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaAdministracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_adminstrationform', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsoTerapeutico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_therepeuticuse', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formadministration_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classifications.formaadministracion')),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.medicamento')),
                ('therepeuticuse_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classifications.usoterapeutico')),
            ],
        ),
    ]
